api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/git"
  id = "paketo-buildpacks/git"
  name = "Paketo Buildpack for Git"

[metadata]
  include-files = [
    "buildpack.toml",
    "linux/amd64/bin/build",
    "linux/amd64/bin/detect",
    "linux/amd64/bin/run",
    "linux/arm64/bin/build",
    "linux/arm64/bin/detect",
    "linux/arm64/bin/run",
  ]

  pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
